name: package_info
description: Flutter plugin for querying information about the application
  package, such as CFBundleVersion on iOS or versionCode on Android.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/package_info
version: 0.3.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.packageinfo
    iosPrefix: FLT
    pluginClass: PackageInfoPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.3.0"
